services:
    file.template.image.library:
        class: Mindy\Bundle\FileBundle\Library\ImageLibrary
        arguments: [ "@=container.get(container.getParameter('file.filesystem'))" ]
        tags:
            - { name: template.library }

    file.form.data_transformer.file:
        class: Mindy\Bundle\FileBundle\Form\DataTransformer\FileDataTransformer
        arguments: [ "@=container.get(container.getParameter('file.filesystem'))" ]

    file.form.extension.file_type:
        class: Mindy\Bundle\FileBundle\Form\Extension\FileExtension
        arguments: [ '@file.form.data_transformer.file' ]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }