parameters:
    file.filesystem: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Mindy\Bundle\FileBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Bundle\FileBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
